// src/components/TopBar.tsx
import React, { type JSX } from 'react'

export default function TopBar(): JSX.Element {
  return (
    <header className="bg-black text-white py-4 px-6 flex justify-between items-center">
      <div className="text-xl font-bold">게젤샤프트</div>
      <nav className="space-x-6 text-center">
        <span>인격</span>
        <span>에고</span>
        <span>덱메이커</span>
        <span>거울던전</span>
      </nav>
    </header>
  )
}

// src/components/common/Topbar.svelte
<!-- filepath: /Users/mac/Documents/게젤샤프트/gesellschaft/src/components/Topbar.svelte -->
<script lang="ts">
</script>

<header
  class="w-full p-4 bg-black text-white flex justify-between items-center"
>
  <div class="text-xl font-bold flex items-center">게젤샤프트</div>
  <nav>
    <ul class="flex gap-4">
      <li><a href="/characters" class="hover:underline text-white">인격</a></li>
      <li><a href="#about" class="hover:underline text-white">에고</a></li>
      <li><a href="#contact" class="hover:underline text-white">전투</a></li>
    </ul>
  </nav>
</header>
